### ISSUE TITLE
CSP Algorithmic Final Ticket

### ISSUE THREAD

**Issue by Archkitten** [Archkitten/CS-AP-2#11]
# Overall Score: 10/10
## Graded by Michael Chen

--------------------------------------------------

[Video](https://youtu.be/sQAuUaaWoz8)
[Feedback](https://github.com/Archkitten/CS-AP-2/issues/11#issuecomment-1089314439)

--------------------------------------------------

GitHub Pages: [Link](https://archkitten.github.io/CS-AP-2/csp/csp_final)
Runtime: [Link](https://archkitten.github.io/CS-AP-2/csp)

**Comment by Michaelc179** [comment]
# Overall Score: 10/10


## Graded by Michael Chen

- [x] 2 Minute Video

The code is very organized in OOP format. Although it is confusing to me, I am sure Arch understands it perfectly because all his code works fine and is organized well.
*  There are several examples of lists and navigation from `menu.py`, `option.py`, and `main.py`. Main also has `week_0.py` for submenus with `build_stairs.py` as an option for animations. 
* Lists and loops are found in `info_loop.py`
* For class understanding, Arch has:
   * Animations from matrixes, stairs, and a cat animation
   * Math: swap, Fibonacci, factorial, triangles, and a multiplication table special challenge (also fulfills enhances learning from python)
   * Data structures are found in the palindrome code and info loops.

Crossover Contributions:
* Arch fixed several errors in the repository
* Commits are found [here](https://github.com/Archkitten/sleep/commits/main)
* He also made several commits to the GitHub pages: [commits](https://github.com/Archkitten/sleep/commits/gh-pages)
